language: r
os: linux
dist: xenial
r:
 - release
cache: packages
warnings_are_errors: true
r_build_args: '--compact-vignettes="gs+qpdf"'
r_check_args: '--no-manual --no-vignettes --as-cran'
env:
 - _R_CHECK_FORCE_SUGGESTS_=false

git:
  depth: 1

addons:
  apt:
    packages:
      - ghostscript

r_binary_packages:
 - ape
 - devtools
 - knitr
 - rmarkdown
 - roxygen2

before_script:
 - R -e "devtools::document()"
 - chmod +x ./_build.sh
 - chmod +x ./_deploy.sh

script:
  - travis_wait 43 ./_build.sh
  - ./_deploy.sh
