---
title: "Node support efficacy in Congreve & Lamsdell matrices"
author: "Martin R. Smith <martin.smith@durham.ac.uk>"
date: "`r Sys.Date()`"
output: 
  html_document:
    default: yes
  bookdown::pdf_document2:
    toc: yes
    includes:
      in_header: ../inst/preamble.tex
bibliography: ../inst/REFERENCES.bib
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/dependent/biology-letters.csl
link-citations: yes
github-repo: ms609/Quartet
vignette: >
  %\VignetteIndexEntry{Results of data analysis}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
---

This page depicts the analytical results of all 100 matrices generated by
Congreve & Lamsdell [-@Congreve2016] using a ternary plotting approach
[@Smith2019], with quartets and partitions used as distance metrics.

```{r initialize, echo=FALSE, message=FALSE}
x <- Sys.setlocale("LC_ALL", "English_United Kingdom.1252") # allows PCH=183
library("Quartet")
library("Ternary")
library("CongreveLamsdell2016")
data('clBremPartitions', 'clBremQuartets', 'clMkvPartitions', 'clMkvQuartets',
     'clBootFreqPartitions', 'clBootFreqQuartets', 
     'clBootGcPartitions', 'clBootGcQuartets',
     'clJackFreqPartitions', 'clJackFreqQuartets',
     'clJackGcPartitions', 'clJackGcQuartets', 
     'clCI')
```

```{r initialize-variables, echo=FALSE}
PCH_MK <- 1   # circle
PCH_EQ <- 61  #'='
PCH_XX <- 18 # 183 #'.' is invalid in some locales
PCH_IW <- 2   #triup
PCH_IC <- 17  #triupfilled
TREE <- 2

COL <- c(
  'mk' = paste0(cbPalette8[4],  '99'),
  'eq' = paste0(cbPalette8[8],  '99'),
  'k1' = paste0(cbPalette8[6],  '42'),
  'k2' = paste0(cbPalette8[6],  '42'),
  'k3' = paste0(cbPalette8[6],  '42'),
  'k5' = paste0(cbPalette8[6],  '42'),
  'kX' = paste0(cbPalette8[6],  '99'),
  'kC' = paste0(cbPalette8[2],  '99'))

GRID_COL <- rgb(0.92, 0.92, 0.92)
BG_COL   <- rgb(0.985, 0.985, 0.992)


MARGINS <- c(2.8, 0.3, 0.3, 0.3)
ROWS <- c(20, 3)

TernaryQuarts <- function(TREE=TREE, an='eq', zoom=1, padding=0.1) {
  
  clInitializeTernaryQuarts(zoom=zoom, padding=padding)
  
  clPlotQuartets(pch=0, clBremQuartets[an], TREE, cex=1.1)
  clPlotQuartets(pch=1, clBootFreqQuartets[an], TREE, cex=1.1)
  clPlotQuartets(pch=2, clBootGcQuartets[an], TREE, cex=1.1)
  clPlotQuartets(pch=4, clJackFreqQuartets[an], TREE, cex=1.1)
  clPlotQuartets(pch=5, clJackGcQuartets[an], TREE, cex=1.1)
  
  clPlotQuartets(pch=1, clMkvQuartets, TREE, cex=1.1, col=COL['mk'])
  
  # Return:
  invisible()
}


TernaryParts<-function(TREE=TREE, an='eq') {
  
  MapToAxes <- function (item) {
    rbind(item[, 'ref'] - item[, 'cf'], 
          item[, 'cf_not_ref'], item[, 'cf_and_ref'])
  }
  
  clInitializeTernarySplits()
  title(main="\nPartitions", cex.main=0.8)
  
  HorizontalGrid(19)
  
  clPlotSplits(pch=1, clBremPartitions[an], TREE)
  clPlotSplits(pch=2, clBootGcPartitions[an], TREE)
  clPlotSplits(pch=3, clBootFreqPartitions[an], TREE)
  clPlotSplits(pch=4, clJackGcPartitions[an], TREE)
  clPlotSplits(pch=5, clJackFreqPartitions[an], TREE)
  
  # Return:
  invisible()
}

AddLegend <- function(pos='bottomright', an='eq') {
  legend(pos, cex=0.8, bty='n',
         lty=1,
         pch=c(PCH_MK, 0:4), pt.cex=1.1,
         col=c(COL['mk'], rep(COL[an], 5)),
         legend=c('Markov', 'Bremer', 'BootFreq', 'Boot GC', 'Jack Freq', 'Jack GC')
   )
}

CompareNodeSupports <- function (i) { 
  
  TernaryQuarts(TREE=i, an='eq')
  title(main=paste0("\nQuartets"), cex.main=0.8)
  arrows(sqrt(3/4) * 0.5, 0.5, sqrt(3/4) * 0.8, 0.5, length=0.1)
  text  (sqrt(3/4) * 0.65, 0.5, pos=3, 'Decreasing resolution', cex=0.8)
  
  arrows(sqrt(3/4) * 0.98, 0.40, sqrt(3/4) * 0.98, 0.20, length=0.1)
  text  (sqrt(3/4) * 1.01, 0.30, pos=3, 'Increasing divergence', cex=0.8, srt=270)
  
  TernaryQuarts(TREE=i, an='eq', zoom=3, padding=0.01)
  title(main=paste0("\nDataset ", i, ": CI=",round(clCI[i], 2)), cex.main=1.2)
  
  TernaryParts(TREE=i, an='eq')
  
  arrows(sqrt(3/4) * 0.98, 0.40, sqrt(3/4) * 0.98, 0.20, length=0.1)
  text  (sqrt(3/4) * 1.01, 0.30, pos=3, 'Increasing RF distance', cex=0.8, srt=270)
  
  AddLegend(an='eq')
  
  TernaryQuarts(TREE=i, an='k3')
  title(main=paste0("\nQuartets"), cex.main=0.8)
  arrows(sqrt(3/4) * 0.5, 0.5, sqrt(3/4) * 0.8, 0.5, length=0.1)
  text  (sqrt(3/4) * 0.65, 0.5, pos=3, 'Decreasing resolution', cex=0.8)
  
  arrows(sqrt(3/4) * 0.98, 0.40, sqrt(3/4) * 0.98, 0.20, length=0.1)
  text  (sqrt(3/4) * 1.01, 0.30, pos=3, 'Increasing divergence', cex=0.8, srt=270)
  
  TernaryQuarts(TREE=i, an='k3', zoom=3, padding=0.01)
  
  TernaryParts(TREE=i, an='k3')
  
  arrows(sqrt(3/4) * 0.98, 0.40, sqrt(3/4) * 0.98, 0.20, length=0.1)
  text  (sqrt(3/4) * 1.01, 0.30, pos=3, 'Increasing RF distance', cex=0.8, srt=270)
  
  AddLegend(an='k3')
}
```

## Trees 1--10
```{R 1-10, echo=FALSE, fig.width=9, fig.height=30}
par(mfrow=ROWS, mar=MARGINS)
x <- lapply(1:10, CompareNodeSupports)
```

## Trees 11--20
```{R 11-20, echo=FALSE, fig.width=9, fig.height=30}
par(mfrow=ROWS, mar=MARGINS)
x <- lapply(11:20, CompareNodeSupports)
```

## Trees 21--30
```{R 21-30, echo=FALSE, fig.width=9, fig.height=30}
par(mfrow=ROWS, mar=MARGINS)
x <- lapply(21:30, CompareNodeSupports)
```

## Trees 31--40
```{R 31-40, echo=FALSE, fig.width=9, fig.height=30}
par(mfrow=ROWS, mar=MARGINS)
x <- lapply(31:40, CompareNodeSupports)
```

## Trees 41--50
```{R 41-50, echo=FALSE, fig.width=9, fig.height=30}
par(mfrow=ROWS, mar=MARGINS)
x <- lapply(41:50, CompareNodeSupports)
```

## Trees 51--60
```{R 51-60, echo=FALSE, fig.width=9, fig.height=30}
par(mfrow=ROWS, mar=MARGINS)
x <- lapply(51:60, CompareNodeSupports)
```

## Trees 61--70
```{R 61-70, echo=FALSE, fig.width=9, fig.height=30}
par(mfrow=ROWS, mar=MARGINS)
x <- lapply(61:70, CompareNodeSupports)
```

## Trees 71--80
```{R 71-80, echo=FALSE, fig.width=9, fig.height=30}
par(mfrow=ROWS, mar=MARGINS)
x <- lapply(71:80, CompareNodeSupports)
```

## Trees 81--90
```{R 81-90, echo=FALSE, fig.width=9, fig.height=30}
par(mfrow=ROWS, mar=MARGINS)
x <- lapply(81:90, CompareNodeSupports)
```

## Trees 91--100
```{R 91-100, echo=FALSE, fig.width=9, fig.height=30}
par(mfrow=ROWS, mar=MARGINS)
x <- lapply(91:100, CompareNodeSupports)
```

## References
