---
title: "Precision and accuracy in Congreve & Lamsdell matrices"
author: "Martin R. Smith <martin.smith@durham.ac.uk>"
date: "`r Sys.Date()`"
output: 
  html_document:
    default: yes
  bookdown::pdf_document2:
    toc: yes
    includes:
      in_header: ../inst/preamble.tex
bibliography: ../inst/REFERENCES.bib
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/dependent/biology-letters.csl
link-citations: yes
github-repo: ms609/Quartet
vignette: >
  %\VignetteIndexEntry{Results of data analysis}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
---

This page depicts the analytical results of all 100 matrices generated by
Congreve & Lamsdell [-@Congreve2016] using a ternary plotting approach
[@Smith2019], with quartets and partitions used as distance metrics.

```{r initialize, echo=FALSE}
Sys.setlocale("LC_ALL", "English_United Kingdom.1252") # allows PCH=183
library("Quartet")
library("Ternary")
library("CongreveLamsdell2016")
data('clBremPartitions', 'clBremQuartets', 'clMkvPartitions', 'clMkvQuartets',
     'clBootPartitions', 'clBootQuartets', 'clJackPartitions', 'clJackQuartets',
     'clCI')
```

```{r initialize-variables, echo=FALSE}
PCH_MK <- 1   # circle
PCH_EQ <- 61  #'='
PCH_XX <- 18 # 183 #'.' is invalid in some locales
PCH_IW <- 2   #triup
PCH_IC <- 17  #triupfilled
TREE <- 2

COL <- c(
  'mk' = paste0(cbPalette8[4],  '99'),
  'eq' = paste0(cbPalette8[8],  '99'),
  'k1' = paste0(cbPalette8[6],  '42'),
  'k2' = paste0(cbPalette8[6],  '42'),
  'k3' = paste0(cbPalette8[6],  '42'),
  'k5' = paste0(cbPalette8[6],  '42'),
  'kX' = paste0(cbPalette8[6],  '99'),
  'kC' = paste0(cbPalette8[2],  '99'))

GRID_COL <- rgb(0.92, 0.92, 0.92)
BG_COL   <- rgb(0.985, 0.985, 0.992)


MARGINS <- c(2.8, 0.3, 0.3, 0.3)
ROWS <- c(10, 3)

TernaryQuarts<-function(TREE=TREE, zoom=1, padding=0.1) {
  
  xLim <- c(0, sqrt(3/4)/zoom)
  yLim <- c(0.5-(1/zoom), 0.5)
  lab <- if (zoom == 1) c('\nUnresolved', '\n    Different', '     Same') else rep('', 3)
  
  TernaryPlot(lab[1], lab[2], lab[3], point='right', lab.cex=0.8, lab.font=2,
              grid.lty='solid', col=BG_COL, grid.col=GRID_COL, 
              grid.lines=19,  axis.labels = 
                if(zoom==1) round(seq(0, choose(22, 4), length.out=19 + 1), 0)
                else FALSE,
              axis.col=rgb(0.6, 0.6, 0.6), 
              padding=padding, xlim=xLim, ylim=yLim)
  HorizontalGrid(19)
  AddToTernary(lines, list(c(0, 2/3, 1/3), c(1, 0, 0)), lty='dotted', col=cbPalette8[8], lwd=2)
  
  AXES <- c('r2', 'd', 's')
  lapply(names(clBremQuartets), function (weighting) {
    JoinTheDots(clBremQuartets[[weighting]][, AXES, TREE],
                col=COL[weighting], cex=1.1, pch=2)
  })
  
  lapply(names(clBootQuartets), function (weighting) {
    JoinTheDots(clBootQuartets[[weighting]][, AXES, TREE],
                col=COL[weighting], cex=1.1, pch=3)
  })
  
  lapply(names(clJackQuartets), function (weighting) {
    JoinTheDots(clJackQuartets[[weighting]][, AXES, TREE],
                col=COL[weighting], cex=1.1, pch=4)
  })
  
  JoinTheDots(clMkvQuartets[[TREE]][, AXES], col=COL['mk'], cex=1.1, pch=PCH_MK)
  
  # Return:
  invisible()
}


TernaryParts<-function(TREE=TREE) {
  
  MapToAxes <- function (item) {
    rbind(item[, 'ref'] - item[, 'cf'], 
          item[, 'cf_not_ref'], item[, 'cf_and_ref'])
  }
  
  TernaryPlot('Unresolved', 'Different', 'Same', point='right', lab.cex=0.8,
              grid.lines = 19, grid.lty='solid', col=BG_COL, grid.col=GRID_COL, 
              axis.col=rgb(0.6, 0.6, 0.6), 
              padding=0.1, axis.labels = 0:19)
  title(main="\nPartitions", cex.main=0.8)
  
  HorizontalGrid(19)
  
  lapply(names(clBremPartitions), function (weighting) {
    JoinTheDots(MapToAxes(clBremPartitions[[weighting]][, , TREE]),
                col=COL[weighting], cex=1.1, pch=2)
  })
  
  lapply(names(clBootPartitions), function (weighting) {
    JoinTheDots(MapToAxes(clBootPartitions[[weighting]][, , TREE]),
                col=COL[weighting], cex=1.1, pch=3)
  })
  
  lapply(names(clJackPartitions), function (weighting) {
    JoinTheDots(MapToAxes(clJackPartitions[[weighting]][, , TREE]),
                col=COL[weighting], cex=1.1, pch=4)
  })
  
  # Return:
  invisible()
}

AddLegend <- function(pos='bottomright')
  legend(pos, cex=0.8, bty='n',
         lty=1,
         pch=c(PCH_MK, PCH_EQ, PCH_XX, PCH_IW, PCH_XX, PCH_XX, PCH_IW, PCH_IC), pt.cex=1.1,
         col=c(COL['mk'], COL['eq'], COL['kX'], COL['k5'], COL['k3'], COL['k2'], COL['k1'], COL['kC']),
         legend=c('Markov', 'Equal weights', paste0('Implied, k=', c(10, 5, 3, 2, 1, '2..10')))
  )

Plottem <- function (i) { 
  
  TernaryQuarts(TREE=i)
  title(main=paste0("\nQuartets"), cex.main=0.8)
  arrows(sqrt(3/4) * 0.5, 0.5, sqrt(3/4) * 0.8, 0.5, length=0.1)
  text  (sqrt(3/4) * 0.65, 0.5, pos=3, 'Decreasing resolution', cex=0.8)
  
  arrows(sqrt(3/4) * 0.98, 0.40, sqrt(3/4) * 0.98, 0.20, length=0.1)
  text  (sqrt(3/4) * 1.01, 0.30, pos=3, 'Increasing divergence', cex=0.8, srt=270)
  
  TernaryQuarts(TREE=i, zoom=3, padding=0.01)
  title(main=paste0("\nDataset ", i, ": CI=",round(clCI[i], 2)), cex.main=1.2)
  
  TernaryParts(TREE=i)
  
  arrows(sqrt(3/4) * 0.98, 0.40, sqrt(3/4) * 0.98, 0.20, length=0.1)
  text  (sqrt(3/4) * 1.01, 0.30, pos=3, 'Increasing RF distance', cex=0.8, srt=270)
  
  AddLegend()
}
```

## Trees 1--10
```{R 1-10, echo=FALSE, fig.width=9, fig.height=30}
par(mfrow=ROWS, mar=MARGINS)
x <- lapply(1:10, Plottem)
```

## Trees 11--20
```{R 11-20, echo=FALSE, fig.width=9, fig.height=30}
par(mfrow=ROWS, mar=MARGINS)
x <- lapply(11:20, Plottem)
```

## Trees 21--30
```{R 21-30, echo=FALSE, fig.width=9, fig.height=30}
par(mfrow=ROWS, mar=MARGINS)
x <- lapply(21:30, Plottem)
```

## Trees 31--40
```{R 31-40, echo=FALSE, fig.width=9, fig.height=30}
par(mfrow=ROWS, mar=MARGINS)
x <- lapply(31:40, Plottem)
```

## Trees 41--50
```{R 41-50, echo=FALSE, fig.width=9, fig.height=30}
par(mfrow=ROWS, mar=MARGINS)
x <- lapply(41:50, Plottem)
```

## Trees 51--60
```{R 51-60, echo=FALSE, fig.width=9, fig.height=30}
par(mfrow=ROWS, mar=MARGINS)
x <- lapply(51:60, Plottem)
```

## Trees 61--70
```{R 61-70, echo=FALSE, fig.width=9, fig.height=30}
par(mfrow=ROWS, mar=MARGINS)
x <- lapply(61:70, Plottem)
```

## Trees 71--80
```{R 71-80, echo=FALSE, fig.width=9, fig.height=30}
par(mfrow=ROWS, mar=MARGINS)
x <- lapply(71:80, Plottem)
```

## Trees 81--90
```{R 81-90, echo=FALSE, fig.width=9, fig.height=30}
par(mfrow=ROWS, mar=MARGINS)
x <- lapply(81:90, Plottem)
```

## Trees 91--100
```{R 91-100, echo=FALSE, fig.width=9, fig.height=30}
par(mfrow=ROWS, mar=MARGINS)
x <- lapply(91:100, Plottem)
```

## References
