#' 100 simulated data matrices
#'
#'  Contains the 100 simulated matrices generated by Congreve & Lamsdell (2016) using a
#'  heterogeneous Markov-k model, generated from the \link{clReferenceTree} topology, with
#'  all branches sharing an equal length.
#'
#' @format
#'  - `clPhyDat`: A list with 100 entries, each comprising a phyDat object
#' of 55 characters for 22 taxa.
#'  - `clMatrices`: A list with 100 entries, each comprising a list of character
#'  tokens for each simulated character, as read from raw nexus files using
#'  `ape::read.nexus.data`.  The four dummy 'characters' have been removed.
#'
#' @references
#'   - Congreve, C. R. & Lamsdell, J. C. (2016). Implied weighting and its
#'   utility in palaeontological datasets: a study using modelled phylogenetic
#'    matrices. Palaeontology 59(3), 447--465. \doi{10.1111/pala.12236}.
#'   - Congreve, C. R. & Lamsdell, J. C. (2016). Data from: Implied weighting and its
#'   utility in palaeontological datasets: a study using modelled phylogenetic
#'    matrices. Dryad Digital Repository. \doi{10.5061/dryad.7dq0j}.

#'
#' @source \url{http://datadryad.org/resource/doi:10.5061/dryad.7dq0j}
"clPhyDat"

#' @rdname clPhyDat
"clMatrices"

#' Tree topology for matrix simulation
#'
#' The tree topology used to generate the matrices in \code{\link{clMatrices}}
#' Congreve & Lamsdell (2016)
#'
#' @format A single phylogenetic tree saved as an object of class \code{phylo}
#'
#' @references
#'   - Congreve, C. R. & Lamsdell, J. C. (2016). Implied weighting and its
#'   utility in palaeontological datasets: a study using modelled phylogenetic
#'    matrices. Palaeontology 59(3), 447--465. \doi{10.1111/pala.12236}.
#'   - Congreve, C. R. & Lamsdell, J. C. (2016). Data from: Implied weighting and its
#'   utility in palaeontological datasets: a study using modelled phylogenetic
#'    matrices. Dryad Digital Repository. \doi{10.5061/dryad.7dq0j}.
#'
#' @examples
#'   library(ape) # Contains tree plotting functions
#'   data(clReferenceTree)
#'   plot(clReferenceTree)
#'
#' @source Congreve, C. R. & Lamsdell, J. C. (2016). Implied weighting and its
#'   utility in palaeontological datasets: a study using modelled phylogenetic
#'    matrices. Palaeontology 59(3), 447--465. \doi{10.1111/pala.12236}.
"clReferenceTree"

#' @templateVar quartet quartet
#' @template clQuartets
"clQuartets"

#' @templateVar quartet partition
#' @template clQuartets
"clPartitions"

#' Congreve Lamsdell consistency indices
#' @rdname congreveLamsdellMatrices
"clCI"
