#' 100 simulated data matrices 
#'
#'  Contains the 100 simulated matrices generated by Congreve & Lamsdell (2016) using a 
#'  heterogeneous Markov-k model, generated from the \link{referenceTree} topology, with 
#'  all branches sharing an equal length.
#'
#' @format A list with 100 entries, each comprising a phyDat object of 55 characters for 22 taxa
#'
#' @references 
#' \insertRef{Congreve2016}{Quartet}
#' \insertRef{Congreve2016dd}{Quartet}
#'
#' @source \url{http://datadryad.org/resource/doi:10.5061/dryad.7dq0j}
"congreveLamsdellMatrices"

#' Tree topology for matrix simulation
#'
#' The tree topology used to generate the matrices in \code{\link{congreveLamsdellMatrices}} 
#' Congreve & Lamsdell (2016)
#'
#' @format A single phylogenetic tree saved as an object of class \code{phylo}
#'
#' @references 
#' \insertRef{Congreve2016}{Quartet}
#' \insertRef{Congreve2016dd}{Quartet}
#' 
#' @examples 
#'   data(referenceTree)
#'   plot(referenceTree)
#' 
#' @source \insertRef{Congreve2016}{Quartet}
"referenceTree"

#' @templateVar quartet quartet
#' @template clQuartets
"clQuartets"

#' @templateVar quartet partition
#' @template clQuartets
"clPartitions"

#' Congreve Lamsdell consistency indices
#' @rdname congreveLamsdellMatrices
"clCI"

